# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

parameters:
    fintrust.mailer_from: '%env(string:FINTRUST_SMTP_FROM)%'
    fintrust.login_url: '%env(string:FINTRUST_LOGIN_URL)%'
    fintrust.public_url: '%env(default::FINTRUST_PUBLIC_URL)%'
    fintrust.mailer_dsn: '%env(string:MAILER_DSN)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $appSecret: '%kernel.secret%'
            string $projectDir: '%kernel.project_dir%'
            string $fintrustMailerFrom: '%fintrust.mailer_from%'
            string $fintrustLoginUrl: '%fintrust.login_url%'
            string $fintrustPublicUrl: '%fintrust.public_url%'
            string $fintrustMailerDsn: '%fintrust.mailer_dsn%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Twig\AlertExtension:
        tags: ['twig.extension']
